# In this file we put all the secrets to make our app and our database communicate.
# Remember that we can see secret as a special configmap where we manage only the 
# password and other properties that must be keep secret.
# In this particular case we use the secret to store the user and password
# (in base64) that must be used in order to access the postgres database.

apiVersion: v1
kind: Secret
metadata:
  name: psql-secret
type: Opaque
data:
  psql-user: dXNlcg==
  psql-password: cHN3